/-
Copyright (c) 2026 University of Washington Math AI Lab. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bianca Viray, Bryan Boehnke, Grant Yang, George Peykanu, Tianshuo Wang
-/
import Mathlib.RingTheory.Etale.StandardEtale
import Mathlib.RingTheory.Unramified.LocalRing
import Mathlib.RingTheory.Smooth.Flat
import Mathlib.RingTheory.LocalRing.Module
import Mathlib.RingTheory.LocalRing.Quotient
import Mathlib.RingTheory.IsAdjoinRoot

/-!
# Monogenic generators for étale extensions of local rings

Given a finite étale extension `R → S` of local rings, we construct a single generator `β ∈ S`
such that `S ≅ R[X]/(minpoly R β)` as `R`-algebras, and show the derivative `f'(β)` is a unit.
This formalizes Lemma 3.2 of [arXiv:2503.07846](https://arxiv.org/abs/2503.07846) (Balçik et al.).
We also prove the converse: if `S` has such a presentation with unit derivative, then `R → S`
is étale.

## Main results

* `Monogenic.exists_adjoin_eq_top`: a finite étale extension of local rings is generated by a
  single element.
* `Monogenic.isUnit_aeval_derivative_minpoly_of_adjoin_eq_top`: the derivative of the minimal
  polynomial at the generator is a unit.
* `IsAdjoinRootMonic.mkOfAdjoinEqTop'`: if `Algebra.adjoin R {α} = ⊤` and `S` is a finite free
  `R`-module, then `S ≅ R[X]/(minpoly R α)` as an `R`-algebra.
* `IsAdjoinRootMonic.algebra_etale`: the converse — if `S ≅ R[X]/(f)` with `f` monic and
  `f'(root)` a unit, then `R → S` is étale.

## Key intermediate results

* `minpoly.natDegree_le'`: the degree of the minimal polynomial is at most `finrank R S`,
  proved via Cayley–Hamilton.
* `Monogenic.minpoly_map_residue`: for étale extensions, the minimal polynomial reduces to the
  minimal polynomial over the residue field.
* `Monogenic.adjoin_eq_top_of_quotient`: Nakayama-type argument lifting generation from a
  quotient `S/q` to `S`.

## References

* [Balçik et al., *Monogenic generators for étale extensions of local rings*](https://arxiv.org/abs/2503.07846)

## Tags

étale, monogenic, local ring, minimal polynomial
-/

open Polynomial Function RingHom

namespace Monogenic

variable {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]

-- #min_imports in
-- avoid _root_.
/- Minpoly.Basic is missing LinearMap.toMatrixAlgEquiv and Module.finrank -/
/-- For finite free modules over a nontrivial ring,
the degree of the minimal polynomial of any element is bounded by the rank of the module -/
theorem _root_.minpoly.natDegree_le' [Module.Finite R S]
    [Module.Free R S] [Nontrivial R] (α : S) :
    (minpoly R α).natDegree ≤ Module.finrank R S := by
  classical
  have b := Module.Free.chooseBasis R S
  let M := LinearMap.toMatrixAlgEquiv b (Algebra.lmul R S α)
  refine (natDegree_le_natDegree (minpoly.min R α M.charpoly_monic ?_)).trans
    (M.charpoly_natDegree_eq_dim.trans (Module.finrank_eq_card_chooseBasisIndex R S).symm).le
  let h := Matrix.aeval_self_charpoly M
  rwa [aeval_algHom_apply, map_eq_zero_iff _ (LinearMap.toMatrixAlgEquiv b).injective,
    aeval_algHom_apply, map_eq_zero_iff _ Algebra.lmul_injective] at h

-- #find_home! minpoly.natDegree_le'
/-- If `Algebra.adjoin R {α} = ⊤` and `S` is a finite free `R`-module,
then `S ≅ R[X]/(minpoly R α)` as an `R`-algebra.

This avoids the `IsIntegrallyClosed` hypothesis by using Cayley–Hamilton
to bound the degree, quotient rank for the reverse bound, and the Orzech
property for injectivity of the evaluation map. -/
-- R[X] → S
noncomputable def _root_.IsAdjoinRootMonic.mkOfAdjoinEqTop'
  [Module.Finite R S]
  [Module.Free R S] [Nontrivial R]
  {α : S} (hα : Algebra.adjoin R {α} = ⊤) :
    IsAdjoinRootMonic S (minpoly R α) := by
  set f := minpoly R α
  have hf : f.Monic := minpoly.monic (Algebra.IsIntegral.isIntegral α)
  haveI := hf.free_adjoinRoot; haveI := hf.finite_adjoinRoot
  let φ : AdjoinRoot f →ₐ[R] S :=
    AdjoinRoot.liftAlgHom f (Algebra.ofId R S) α (minpoly.aeval R α)
  have hφ_surj : Surjective φ := by
    rw [Algebra.adjoin_singleton_eq_range_aeval, AlgHom.range_eq_top] at hα
    exact fun s =>
      let ⟨p, hp⟩ := hα s; ⟨AdjoinRoot.mk f p, by simp [φ, ← aeval_def, hp]⟩
  have hrank : f.natDegree = Module.finrank R S := le_antisymm (minpoly.natDegree_le' α) (by
    have e := φ.toLinearMap.quotKerEquivRange.trans
      (LinearEquiv.ofTop _ (LinearMap.range_eq_top.mpr hφ_surj))
    rw [← e.finrank_eq]
    exact (Submodule.finrank_quotient_le _).trans (finrank_quotient_span_eq_natDegree' hf).le)
  have e := LinearEquiv.ofFinrankEq (R := R) (AdjoinRoot f) S
    ((finrank_quotient_span_eq_natDegree' hf).trans hrank)
  have hφ_inj : Injective φ := fun x y h => OrzechProperty.injective_of_surjective_endomorphism
    (e.symm.toLinearMap.comp φ.toLinearMap) (e.symm.surjective.comp hφ_surj) (congr_arg e.symm h)
  exact
    { IsAdjoinRoot.ofAdjoinRootEquiv
        (AlgEquiv.ofBijective φ ⟨hφ_inj, hφ_surj⟩) with monic := hf }

lemma mkOfAdjoinEqTop'_map
    [Module.Finite R S]
    [Module.Free R S] [Nontrivial R]
    {α : S} {hα : Algebra.adjoin R {α} = ⊤} :
    (IsAdjoinRootMonic.mkOfAdjoinEqTop' hα).map = (aeval α) := by
  unfold IsAdjoinRootMonic.mkOfAdjoinEqTop'
  ext; simp

/-!
## Helper lemmas for the derivative unit condition

A key fact from Lemma 3.2 of [arXiv:2503.07846](https://arxiv.org/abs/2503.07846)
is that for a finite étale extension of local rings, the derivative of the
minimal polynomial evaluated at the generator is a unit.

The proof proceeds through the residue fields:
1. Since `R -> S` is étale, the residue field extension `R / m_R → S / m_S` is separable
2. For separable extensions, the minimal polynomial is separable.
3. Separable polynomial ⟹ derivative at root is non-zero
4. Non-zero in residue field ⟹ unit in local ring
-/

-- For a local ring `S`, we denote its maximal ideal by `m_S`.
variable [IsLocalRing S]

variable [IsLocalRing R] [Module.Finite R S] [FaithfulSMul R S]

-- Mathlib.RingTheory.LocalRing.ResidueField.Basic?
/-- When `β` generates `S` over `R`, the residue `β₀ = β mod m_S`
generates `S/m_S` over `R/m_R`. -/
lemma adjoin_residue_eq_top_of_adjoin_eq_top
    {β : S} (hβ_gen : Algebra.adjoin R {β} = ⊤) :
    Algebra.adjoin (IsLocalRing.ResidueField R) {IsLocalRing.residue S β} = ⊤ := by
  rw [Algebra.adjoin_singleton_eq_range_aeval, AlgHom.range_eq_top] at *
  intro x
  obtain ⟨s, rfl⟩ := IsLocalRing.residue_surjective (R := S) x
  obtain ⟨p, rfl⟩ := hβ_gen s
  exact ⟨p.map (IsLocalRing.residue R),
    (map_aeval_eq_aeval_map (ψ := IsLocalRing.residue S)
      (φ := IsLocalRing.residue R) rfl p β).symm⟩

-- Q: Is this in the right level of generality?
-- consider adding the maximal ideals mapping as an explicit
-- hypothesis instead of using Algebra.Etale.
/-- For finite étale extensions of local rings,
`finrank R S = finrank (ResidueField R) (ResidueField S)`. -/
lemma finrank_eq_finrank_residueField [Algebra.Etale R S] :
    Module.finrank R S =
      Module.finrank (IsLocalRing.ResidueField R) (IsLocalRing.ResidueField S) := by
  haveI : Module.Free R S := Module.free_of_flat_of_isLocalRing
  have hmaximal : Ideal.map (algebraMap R S) (IsLocalRing.maximalIdeal R) =
      IsLocalRing.maximalIdeal S := Algebra.FormallyUnramified.map_maximalIdeal
  let e : (S ⧸ Ideal.map (algebraMap R S) (IsLocalRing.maximalIdeal R))
      ≃ₗ[R ⧸ IsLocalRing.maximalIdeal R] (S ⧸ IsLocalRing.maximalIdeal S) :=
    AddEquiv.toLinearEquiv (Ideal.quotEquivOfEq hmaximal).toAddEquiv (fun r x => by
      obtain ⟨r, rfl⟩ := Ideal.Quotient.mk_surjective r
      obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective x
      simp only [RingEquiv.toAddEquiv_eq_coe]; rfl)
  erw [← e.finrank_eq, IsLocalRing.finrank_quotient_map (R := R) (S := S)]

/-- For a monogenic étale extension of local rings, the minimal polynomial of `β`
maps to the minimal polynomial of `β mod m_S` over the residue field. -/
lemma minpoly_map_residue [Algebra.Etale R S]
    {β : S} (hadj : Algebra.adjoin R {β} = ⊤) :
    (minpoly R β).map (IsLocalRing.residue R) = minpoly (IsLocalRing.ResidueField R)
      (IsLocalRing.residue S β) := by
  have hmonic := minpoly.monic <| Algebra.IsIntegral.isIntegral (R:=R) β
  let kR := IsLocalRing.ResidueField R
  let β₀ := IsLocalRing.residue S β
  let f_bar := (minpoly R β).map (IsLocalRing.residue R)
  have hβ₀_int : IsIntegral kR β₀ := Algebra.IsIntegral.isIntegral β₀
  -- β₀ is a root of f_bar, so minpoly kR β₀ divides f_bar
  have hdvd : minpoly kR β₀ ∣ f_bar := minpoly.dvd kR β₀ (by
    rw [← map_aeval_eq_aeval_map (ψ := IsLocalRing.residue S)
      (φ := IsLocalRing.residue R) rfl, minpoly.aeval, map_zero])
  have hβ₀_gen : Algebra.adjoin kR {β₀} = ⊤ := adjoin_residue_eq_top_of_adjoin_eq_top hadj
  -- Degree chain: natDegree f_bar = natDegree f = finrank R S
  --             = finrank kR kS = natDegree (minpoly kR β₀)
  have hβ₀_field_gen : IntermediateField.adjoin kR {β₀} = ⊤ := by
    rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
      (Algebra.IsAlgebraic.isAlgebraic β₀)] at hβ₀_gen
    exact IntermediateField.toSubalgebra_injective hβ₀_gen
  have hdeg_eq : f_bar.natDegree = (minpoly kR β₀).natDegree := by
    haveI : Module.Free R S := Module.free_of_flat_of_isLocalRing
    rw [hmonic.natDegree_map _,
      ← (IsAdjoinRootMonic.mkOfAdjoinEqTop' hadj).finrank,
      finrank_eq_finrank_residueField, ← IntermediateField.finrank_top', ← hβ₀_field_gen,
      IntermediateField.adjoin.finrank hβ₀_int]
  -- Both monic, same degree, divisibility ⟹ equal
  exact eq_of_monic_of_dvd_of_natDegree_le (minpoly.monic hβ₀_int)
    (hmonic.map _) hdvd hdeg_eq.le

/-- If `R → S` is étale and `R[β] = S`, then `f'(β)` is a unit in `S`,
where `f = minpoly R β`. The proof reduces to separability of the
residue field extension via `minpoly_map_residue`. -/
lemma isUnit_aeval_derivative_minpoly_of_adjoin_eq_top
    [Algebra.Etale R S] {β : S}
    (hadj : Algebra.adjoin R {β} = ⊤) :
    IsUnit (aeval β (minpoly R β).derivative) := by
  -- Strategy: show residue of (aeval β f') is non-zero, hence aeval β f' is a unit
  apply fun s => (IsLocalRing.residue_ne_zero_iff_isUnit s).mp
  let kR := IsLocalRing.ResidueField R
  let β₀ := IsLocalRing.residue S β
  -- Therefore, derivative of minpoly at β₀ is non-zero
  rw [map_aeval_eq_aeval_map (ψ := IsLocalRing.residue S)
    (φ := IsLocalRing.residue R) rfl, ← derivative_map, minpoly_map_residue hadj]
  exact (Algebra.IsSeparable.isSeparable kR β₀).aeval_derivative_ne_zero (minpoly.aeval kR β₀)

/-!
## Nakayama helpers for the quotient-lifting argument

These lemmas support the proof that `Algebra.adjoin R {β} = ⊤` when β generates
the quotient `S/q` over `R/(q ∩ R)`, and a suitable element π ∈ Algebra.adjoin R {β}
generates the maximal ideal modulo `mR · S`.
-/

omit [IsLocalRing S] [IsLocalRing R] [Module.Finite R S] [FaithfulSMul R S] in
/-- If `I = ⟨π⟩ + J`, then `I^k ≤ ⟨π^k⟩ + J`. Pure ideal arithmetic. -/
lemma Ideal.pow_le_span_pow_sup {I J : Ideal S} {π : S}
    (h : I = Ideal.span {π} ⊔ J) (k : ℕ) :
    I ^ k ≤ Ideal.span {π ^ k} ⊔ J := by
  induction k with
  | zero => simp [Ideal.span_singleton_one]
  | succ k ih =>
    rw [pow_succ]; exact (Ideal.mul_mono ih h.le).trans (by
      rw [Ideal.sup_mul, Ideal.mul_sup, Ideal.mul_sup]; exact sup_le (sup_le
        (by rw [Ideal.span_singleton_mul_span_singleton, pow_succ]; exact le_sup_left)
        (Ideal.mul_le_left.trans le_sup_right))
        (sup_le (Ideal.mul_le_right.trans le_sup_right)
          (Ideal.mul_le_left.trans le_sup_right)))

omit [IsLocalRing S] [IsLocalRing R] [Module.Finite R S] [FaithfulSMul R S] in
/-- If `(R/p)[β] = S/q` where `p = q.comap φ`, then every element of `S`
is congruent to an element of `R[β]` modulo `q`. -/
lemma exists_adjoin_sub_mem
    (β : S) (q : Ideal S)
    (h_gen : Algebra.adjoin (R ⧸ q.comap (algebraMap R S))
      {Ideal.Quotient.mk q β} = ⊤) (s : S) :
    ∃ t ∈ Algebra.adjoin R {β}, s - t ∈ q := by
  rw [Algebra.adjoin_singleton_eq_range_aeval, AlgHom.range_eq_top] at h_gen
  obtain ⟨p, hp⟩ := h_gen (Ideal.Quotient.mk q s)
  obtain ⟨r, rfl⟩ := Polynomial.map_surjective _ Ideal.Quotient.mk_surjective p
  refine ⟨aeval β r, ?_, Ideal.Quotient.eq.mp ?_⟩
  · rw [Algebra.adjoin_singleton_eq_range_aeval]; exact ⟨r, rfl⟩
  · rw [map_aeval_eq_aeval_map (ψ := Ideal.Quotient.mk q)
      (φ := Ideal.Quotient.mk (q.comap (algebraMap R S)))
      (by ext; exact (Ideal.quotientMap_mk (I := q) (f := algebraMap R S)
        (H := le_rfl)).symm), hp]

omit [IsLocalRing S] [IsLocalRing R] [Module.Finite R S] [FaithfulSMul R S] in
/-- Iterative approximation: each `x` can be approximated by an element
of `A` modulo `⟨π^k⟩ + mR·S`. -/
lemma exists_sub_mem_adjoin_of_pow
    {A : Subalgebra R S} {q ms mR_S : Ideal S} {π : S}
    (h_lift : ∀ s : S, ∃ t ∈ A, s - t ∈ q)
    (hπ_mem : π ∈ A) (hπ_ms : π ∈ ms) (hq_le : q ≤ ms)
    (h_ms : ms = Ideal.span {π} ⊔ mR_S)
    (k : ℕ) (x : S) :
    ∃ a ∈ A.toSubmodule, x - a ∈ (Ideal.span {π ^ k} ⊔ mR_S : Ideal S) := by
  induction k with
  | zero => exact ⟨0, Subalgebra.zero_mem A, by simp [Ideal.span_singleton_one]⟩
  | succ k ih =>
    obtain ⟨a₀, ha₀, hz⟩ := ih
    obtain ⟨y, hy, r, hr, hyr⟩ := Submodule.mem_sup.mp hz
    obtain ⟨c, rfl⟩ := Ideal.mem_span_singleton.mp hy
    obtain ⟨a₁, ha₁, hc⟩ := h_lift c
    refine ⟨a₀ + a₁ * π ^ k, Subalgebra.add_mem A ha₀
      (Subalgebra.mul_mem A ha₁ (Subalgebra.pow_mem A hπ_mem k)), ?_⟩
    rw [show x - (a₀ + a₁ * π ^ k) = π ^ k * (c - a₁) + r from
      by linear_combination hyr.symm]
    exact Ideal.add_mem _ (Ideal.pow_le_span_pow_sup h_ms (k + 1) (by
      rw [pow_succ]
      exact Ideal.mul_mem_mul (Ideal.pow_mem_pow hπ_ms k) (hq_le hc)))
      (Ideal.mem_sup_right hr)

omit [IsLocalRing S] [IsLocalRing R] [Module.Finite R S] [FaithfulSMul R S] in
/-- If `(R/p)[β] = S/q` and `m_S = ⟨π⟩ + m_R · S` for some `π ∈ R[β]`,
then `R[β] = S`. The proof combines quotient lifting, Artinian descent
on `S/m_R·S`, iterative approximation, and Nakayama's lemma. -/
lemma adjoin_eq_top_of_quotient
    [IsLocalRing R] [IsLocalRing S] [Module.Finite R S]
    (β : S) (q : Ideal S) [q.IsPrime]
    (h_gen : Algebra.adjoin (R ⧸ q.comap (algebraMap R S))
      {Ideal.Quotient.mk q β} = ⊤)
    (π : S) (hπ_mem : π ∈ Algebra.adjoin R {β})
    (h_ms : IsLocalRing.maximalIdeal S =
      Ideal.span {π} ⊔ Ideal.map (algebraMap R S) (IsLocalRing.maximalIdeal R)) :
    Algebra.adjoin R {β} = ⊤ := by
  set A := Algebra.adjoin R {β}; set mR := IsLocalRing.maximalIdeal R
  set ms := IsLocalRing.maximalIdeal S; set mR_S := Ideal.map (algebraMap R S) mR
  haveI : IsArtinianRing (S ⧸ mR_S) := by
    letI := Ideal.Quotient.field mR
    haveI := Module.Finite.of_restrictScalars_finite R (R ⧸ mR) (S ⧸ mR_S)
    exact IsArtinianRing.of_finite (R ⧸ mR) (S ⧸ mR_S)
  obtain ⟨n, hn⟩ := IsLocalRing.exists_maximalIdeal_pow_le_of_isArtinianRing_quotient mR_S
  have h_lift := exists_adjoin_sub_mem β q h_gen
  have hπ_ms : π ∈ ms := h_ms ▸ Ideal.mem_sup_left (Ideal.mem_span_singleton_self π)
  have hq_le : q ≤ ms := IsLocalRing.le_maximalIdeal (Ideal.IsPrime.ne_top ‹_›)
  have h_q : (q.restrictScalars R : Submodule R S) ≤ A.toSubmodule ⊔ mR • ⊤ := by
    intro x hx
    obtain ⟨a, ha, hxa⟩ := exists_sub_mem_adjoin_of_pow h_lift hπ_mem hπ_ms hq_le h_ms n x
    rw [Ideal.smul_top_eq_map]
    exact Submodule.mem_sup.mpr ⟨a, ha, x - a, show x - a ∈ mR_S.restrictScalars R from
      (sup_le (Ideal.span_le.mpr (Set.singleton_subset_iff.mpr
        (hn (Ideal.pow_mem_pow hπ_ms n)))) le_rfl) hxa, by ring⟩
  exact eq_top_iff.mpr (Submodule.le_of_le_smul_of_le_jacobson_bot
    (Module.finite_def.mp inferInstance) (IsLocalRing.maximalIdeal_le_jacobson ⊥) (by
      intro s _; obtain ⟨t, ht, hst⟩ := h_lift s
      rw [show s = t + (s - t) from by ring]
      exact Submodule.add_mem _ (Submodule.mem_sup_left ht) (h_q hst)))

/-- A finite étale extension of local rings is generated by a single element.
This is Lemma 3.2, part 1 of [arXiv:2503.07846](https://arxiv.org/abs/2503.07846).
The proof lifts a primitive element of the residue field extension via Nakayama's lemma. -/
theorem exists_adjoin_eq_top [Algebra.Etale R S] :
    ∃ β : S, Algebra.adjoin R {β} = ⊤ := by
  obtain ⟨β₀, hβ₀⟩ := Field.exists_primitive_element (IsLocalRing.ResidueField R)
    (IsLocalRing.ResidueField S)
  obtain ⟨β, hβ⟩ := Ideal.Quotient.mk_surjective β₀
  refine ⟨β, ?_⟩
  have h_adjoin_top : Algebra.adjoin (IsLocalRing.ResidueField R) {β₀} = ⊤ := by
    rw [← IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic
      (Algebra.IsAlgebraic.isAlgebraic β₀), hβ₀, IntermediateField.top_toSubalgebra]
  rw [show β₀ = IsLocalRing.residue S β from hβ.symm,
    Algebra.adjoin_singleton_eq_range_aeval, AlgHom.range_eq_top] at h_adjoin_top
  set mR := IsLocalRing.maximalIdeal R
  have h_le_sup : (⊤ : Submodule R S) ≤ (Algebra.adjoin R {β}).toSubmodule ⊔ mR • ⊤ := by
    intro s _
    obtain ⟨p, hp⟩ := h_adjoin_top (IsLocalRing.residue S s)
    obtain ⟨q, rfl⟩ := Polynomial.map_surjective _ IsLocalRing.residue_surjective p
    rw [Ideal.smul_top_eq_map]
    refine Submodule.mem_sup.mpr ⟨aeval β q, ?_, s - aeval β q, ?_, by ring⟩
    · rw [Algebra.adjoin_singleton_eq_range_aeval]; exact ⟨q, rfl⟩
    · exact (Algebra.FormallyUnramified.map_maximalIdeal (R := R) (S := S)) ▸
        Ideal.Quotient.eq.mp
          (show IsLocalRing.residue S s = IsLocalRing.residue S (aeval β q) by
            rw [map_aeval_eq_aeval_map (ψ := IsLocalRing.residue S)
              (φ := IsLocalRing.residue R) rfl, hp])
  exact eq_top_iff.mpr (Submodule.le_of_le_smul_of_le_jacobson_bot
    (Module.finite_def.mp inferInstance) (IsLocalRing.maximalIdeal_le_jacobson ⊥) h_le_sup)

/-!
## Converse: monogenic with unit derivative implies étale

The converse direction: if `S ≅ R[X]/(f)` with `f` monic and `f'(root)` a unit,
then the algebra map `R → S` is étale. This completes the characterization:
for finite local extensions, étale with single generator is equivalent to
monogenic with unit derivative (i.e., standard étale).
-/

omit [IsLocalRing S] [IsLocalRing R] [Module.Finite R S] [FaithfulSMul R S] in
/-- If `S ≅ R[X]/(f)` with `f` monic and `f'(root)` a unit in `S`, then `R → S` is étale.
This is the converse of `isUnit_aeval_derivative_minpoly`: together they show that
for finite extensions of local rings, the étale condition is equivalent to
being a monogenic extension with unit derivative.

The proof constructs a `StandardEtalePresentation` using the pair `(f, f')`:
since `f' · 1 + f · 0 = f'^1`, the derivative condition gives the Bézout-type
relation needed for standard étaleness. -/
theorem _root_.IsAdjoinRootMonic.algebra_etale
    {f : R[X]} (adj : IsAdjoinRootMonic S f)
    (hunit : IsUnit (aeval adj.root f.derivative)) :
    Algebra.Etale R S := by
  set P : StandardEtalePair R := ⟨f, adj.monic, f.derivative, 1, 0, 1, by ring⟩
  have hmap : P.HasMap adj.root := ⟨adj.aeval_root_self, hunit⟩
  set e := adj.toIsAdjoinRoot.adjoinRootAlgEquiv with he
  set bwd : S →ₐ[R] P.Ring :=
    (AdjoinRoot.liftAlgHom f _ P.X P.hasMap_X.1).comp e.symm.toAlgHom with hbwd
  have h_inv : ∀ x, bwd (P.lift adj.root hmap x) = x := DFunLike.congr_fun
    (show bwd.comp (P.lift adj.root hmap) = AlgHom.id R P.Ring from by
      apply P.hom_ext; change bwd (P.lift adj.root hmap P.X) = P.X; simp [hbwd, he])
  have h_right : ∀ s, P.lift adj.root hmap (bwd s) = s := by
    intro s; obtain ⟨p, rfl⟩ := adj.map_surjective s
    have : bwd (adj.map p) = aeval P.X p := by
      change (AdjoinRoot.liftAlgHom f _ P.X P.hasMap_X.1) (e.symm (adj.map p)) = _
      rw [e.symm_apply_eq.mpr (adj.toIsAdjoinRoot.adjoinRootAlgEquiv_apply_mk p).symm]
      simp [aeval_def]
    rw [this, ← aeval_algHom_apply, P.lift_X]; simp
  exact haveI : Algebra.IsStandardEtale R S := ⟨⟨P, adj.root, hmap,
    fun a b h => by rw [← h_inv a, ← h_inv b, h],
    fun s => ⟨bwd s, h_right s⟩⟩⟩; inferInstance

end Monogenic
